service: animal-recognizer
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.11
  region: ${env:REGION}
  stage: ${env:STAGE}

functions:
  animal-recognizer:
    image: ${env:AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/animal-recognizer-lambda-image:latest
    timeout: 360
    memorySize: 3008
    architecture: arm64
    environment:
      FRAME_DYNAMO_TABLE: ${env:FRAME_DYNAMO_TABLE}
      FRAME_S3_BUCKET: ${env:FRAME_S3_BUCKET}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::${env:FRAME_S3_BUCKET}/*
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:${env:AWS_ACCOUNT_ID}:table/${env:FRAME_DYNAMO_TABLE}
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${env:AWS_ACCOUNT_ID}:${env:FRAME_SQS_NAME}
