createFrame:
  handler: src/lambdas/http/post-frame.handler
  # environment:
  #   FRAME_TABLE: !Ref RoomTable
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:PutItem
  #     Resource: !GetAtt VisitEventStoreTable.Arn
  events:
    - http:
        path: frames
        method: post
        # authorizer:
        #   name: UserPoolAuthorizer
        #   type: COGNITO_USER_POOLS
        #   arn: !GetAtt CognitoUserPool.Arn
