service: api
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false
    packager: "yarn"
    excludeFiles: src/**/*.test.ts
  configFile: ${file(config.yml):}
  resourceSlug: api-${self:custom.configFile.STAGE}

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${self:custom.configFile.STAGE}
  region: ${self:custom.configFile.REGION}
  environment:
    STAGE: ${self:provider.stage}

functions:
  - ${file(infrastructure/functions.yml)}
# resources:
#   - ${file(infrastructure/auth.yml)}
#   - ${file(infrastructure/database.yml)}
#   - ${file(infrastructure/queues.yml)}
