service: api
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-add-api-key

package:
  individually: true

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false
    packager: "yarn"
    excludeFiles: src/**/*.test.ts
  configFile: ${file(config.yml):}
  resourceSlug: api-${self:custom.configFile.STAGE}
  apiKeys:
    - name: motion-detector-api-key
      usagePlan:
        name: "motion-detector-usage-plan"
        description: "Used by motion detector to send frames"
        quota:
          limit: 1000
          period: DAY
        throttle:
          burstLimit: 100
          rateLimit: 20

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${self:custom.configFile.STAGE}
  region: ${self:custom.configFile.REGION}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${self:custom.configFile.ACCOUNT_ID}

functions:
  - ${file(infrastructure/functions.yml)}

resources:
  - ${file(infrastructure/auth.yml)}
  - ${file(infrastructure/database.yml)}
  - ${file(infrastructure/queues.yml)}
  - ${file(infrastructure/s3.yml)}
